ARG TAG=@sha256:c35e29c9450151419d9448b0fd75374fec4fff364a27f176fb458d472dfc9e54
FROM ubuntu${TAG} AS builder
COPY requirements.txt /tmp
RUN apt-get update --fix-missing -o Acquire::Retries=3 && \
  apt-get install -y --no-install-recommends python3-pip python3-setuptools python3-dev gcc && \
  python3 -m pip wheel -w /tmp/wheel -r /tmp/requirements.txt

FROM ubuntu${TAG}
LABEL maintainer="support@opennix.ru"
LABEL description="Ubuntu 24.04 Wazuh Docker Agent"
ARG AGENT_VERSION="4.14.1-1"
ENV JOIN_MANAGER_MASTER_HOST=""
ENV JOIN_MANAGER_WORKER_HOST=""
ENV VIRUS_TOTAL_KEY=""
ENV JOIN_MANAGER_PROTOCOL="https"
ENV JOIN_MANAGER_USER=""
ENV JOIN_MANAGER_PASSWORD=""
ENV JOIN_MANAGER_API_PORT="55000"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive
ENV PIP_ROOT_USER_ACTION=ignore
ENV TZ=Etc/UTC

RUN apt-get update --fix-missing -o Acquire::Retries=3 && apt-get install -y --no-install-recommends \
  procps \
  curl \
  apt-transport-https \
  gnupg2 \
  inotify-tools \
  python3-docker \
  python3-setuptools \
  python3-pip && \
  curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh.gpg && \
  echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | \
  tee /etc/apt/sources.list.d/wazuh.list && \
  apt-get update --fix-missing -o Acquire::Retries=3 && apt-get install -y wazuh-agent=${AGENT_VERSION} && \
  mkdir -p /usr/share/man/man1 && \
  apt-get install -y openjdk-11-jdk

COPY *.py *.jinja2  /var/ossec/
WORKDIR /var/ossec/
COPY --from=builder /tmp/wheel /tmp/wheel

RUN pip3 install \
  --ignore-installed \
  --break-system-packages \
  --no-index /tmp/wheel/*.whl && \
  chmod +x /var/ossec/deregister_agent.py && \
  chmod +x /var/ossec/register_agent.py && \
  apt-get clean autoclean && \
  apt-get autoremove -y && \
  rm -rf /var/lib/{apt,dpkg,cache,log}/ && \
  rm -rf  /tmp/* /var/tmp/* /var/log/* && \
  chown -R wazuh:wazuh /var/ossec/
EXPOSE 5000
ENTRYPOINT ["./register_agent.py"]
