name: Build and push docker images

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CodeQL"]
    branches: [main]
    types:
      - completed
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: kennyopennix/wazuh-agent
          - dockerfile: ./images/Dockerfie.amazonlinux
            image: kennyopennix/wazuh-agent-amazonlinux
          - dockerfile: ./images/Dockerfie.ubuntu
            image: kennyopennix/wazuh-agent-ubuntu
          - dockerfile: ./Dockerfile
            image: opennix/wazuh-agent
          - dockerfile: ./images/Dockerfie.amazonlinux
            image: opennix/wazuh-agent-amazonlinux
          - dockerfile: ./images/Dockerfie.ubuntu
            image: opennix/wazuh-agent-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Extract metadata (tags, labels) for Docker
        if: github.ref_type == 'tag' || github.event_name != 'pull_request'
        continue-on-error: true
        id: meta-tag
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push tags
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta-tag.outputs.tags }}
          labels: ${{ steps.meta-tag.outputs.labels }}
